# Cargo audit configuration
[advisories]
# Ignore RSA vulnerability in MySQL driver since we only use PostgreSQL
ignore = [
    "RUSTSEC-2023-0071"  # RSA Marvin Attack - only affects MySQL driver, we use PostgreSQL only
]

[bans]
# No banned crates currently

[licenses]
# Allow common open source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016"
]