version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: github-pg-query-db
    environment:
      POSTGRES_DB: github_pg_query
      POSTGRES_USER: github_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U github_user -d github_pg_query"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: